services:
  signlanguage:
    build:
      context: .
    container_name: signlanguage-container
    ports:
      - "2468:2468"
    restart: always
    volumes:
      - ./assets:/workspace/assets
      - ./db:/workspace/db
      - ./generator:/workspace/generator
      - ./server:/workspace/server
      - ./service:/workspace/service
      - ./utils:/workspace/utils
      - ./web:/workspace/web
    command: ["python3", "/workspace/server/host.py"]

