services:
  signlanguage:
    build:
      context: .
    container_name: siglanguage-container
    ports:
      - "2468:2468"
    restart: always
    environment:
      - PYTHONPATH=/workspace/app
    volumes:
      - ./assets:/workspace/assets
      - ./db:/workspace/db
      - ./generator:/workspace/generator
      - ./server:/workspace/server
      - ./service:/workspace/service
      - ./utils:/workspace/utils
      - ./web:/workspace/web
    command: ["python", "/workspace/app/server/host.py"]

